#!/usr/bin/env python3
"""
Download missing images from the Wayback Machine.

Generated by process_pages.py. Run from the project root:

    python3 download_missing_images.py

If you get 429 Too Many Requests errors, just wait 10-15 minutes
and run again — it skips files that already exist.
"""

import os
import time
import urllib.request
import urllib.error

CANONICAL_TS = "20220319205345"
SITE = "ourladyoflourdesmweahospital.org"
DEST_BASE = os.path.join("web.archive.org", "web", f"{CANONICAL_TS}im_", "http:", SITE)
DELAY = 3
MAX_RETRIES = 5
RETRY_DELAY = 60
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

MISSING_IMAGES = [
    'images/ollmh/Aministration/DSC00488.JPG',
    'images/ollmh/CommunityProject/A',
    'images/ollmh/CommunityProject/COMMUNITY',
    'images/ollmh/CommunityProject/ORPHANS',
    'images/ollmh/hospitalUnits/InPatient/DSCF7526%20(2',
    'images/ollmh/hospitalUnits/Mwea',
    'templates/tx_finnix/images/style1/logo.png&quot;',
]

def download(url, filepath):
    if os.path.exists(filepath) and os.path.getsize(filepath) > 100:
        print(f"  SKIP (exists): {os.path.basename(filepath)}")
        return True
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={
                "User-Agent": USER_AGENT,
                "Accept": "*/*",
            })
            with urllib.request.urlopen(req, timeout=90) as resp:
                data = resp.read()
                os.makedirs(os.path.dirname(filepath), exist_ok=True)
                with open(filepath, "wb") as f:
                    f.write(data)
                return True
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = RETRY_DELAY * attempt
                print(f"  429 rate-limited – retry {attempt}/{MAX_RETRIES} in {wait}s …")
                time.sleep(wait)
            elif e.code in (404, 410):
                print(f"  HTTP {e.code} – not found: {url}")
                return False
            else:
                print(f"  HTTP {e.code}: {e.reason}")
                return False
        except Exception as e:
            print(f"  Error: {e}")
            if attempt < MAX_RETRIES:
                time.sleep(DELAY * attempt)
    return False


def main():
    print("=" * 64)
    print("  Download Missing Images from Wayback Machine")
    print("=" * 64)
    print(f"  Images to download: {len(MISSING_IMAGES)}")
    print(f"  Output folder: {DEST_BASE}/")
    print("=" * 64 + "\n")

    ok = 0
    fail = 0
    for i, path in enumerate(MISSING_IMAGES, 1):
        url = f"https://web.archive.org/web/{CANONICAL_TS}im_/http://{SITE}/{path}"
        filepath = os.path.join(DEST_BASE, path)
        print(f"[{i}/{len(MISSING_IMAGES)}] {os.path.basename(path)}")
        if download(url, filepath):
            ok += 1
        else:
            fail += 1
        time.sleep(DELAY)

    print(f"\n  Done: {ok} downloaded, {fail} failed")


if __name__ == "__main__":
    main()
