#!/usr/bin/env python3
"""
Download missing images from the Wayback Machine.

Generated by process_pages.py. Run from the project root:

    python3 download_missing_images.py

If you get 429 Too Many Requests errors, just wait 10-15 minutes
and run again — it skips files that already exist.
"""

import os
import time
import urllib.request
import urllib.error

CANONICAL_TS = "20220319205345"
SITE = "ourladyoflourdesmweahospital.org"
DEST_BASE = os.path.join("web.archive.org", "web", f"{CANONICAL_TS}im_", "http:", SITE)
DELAY = 3
MAX_RETRIES = 5
RETRY_DELAY = 60
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

MISSING_IMAGES = [
    'images/GA_PRGlobalFutures503.jpg',
    'images/ollmh/Aministration/0llmhadminblock.jpg',
    'images/ollmh/Aministration/Administrator.jpg',
    'images/ollmh/Aministration/DSC00488.JPG',
    'images/ollmh/Aministration/SrJosephine.jpg',
    'images/ollmh/Aministration/nusingadminBlock.jpg',
    'images/ollmh/CommunityProject/A',
    'images/ollmh/CommunityProject/COMMUNITY',
    'images/ollmh/CommunityProject/Faith%20giving%20health%20talk%20-%20Copy.JPG',
    'images/ollmh/CommunityProject/JiggersProject/DSC07763.JPG',
    'images/ollmh/CommunityProject/JiggersProject/DSC07766.JPG',
    'images/ollmh/CommunityProject/JiggersProject/DSC07771.JPG',
    'images/ollmh/CommunityProject/ORPHANS',
    'images/ollmh/S.M.IMwea/DSC09126.JPG',
    'images/ollmh/S.M.IMwea/JosewithSreldest.JPG',
    'images/ollmh/S.M.IMwea/SRSOpensch.JPG',
    'images/ollmh/S.M.IMwea/Sroldest.JPG',
    'images/ollmh/S.M.IMwea/srs_CA.JPG',
    'images/ollmh/Sustainability_Projects/2013maizefarming/DSC06228.JPG',
    'images/ollmh/Sustainability_Projects/2013maizefarming/DSC06229.JPG',
    'images/ollmh/Sustainability_Projects/2013maizefarming/DSC06230.JPG',
    'images/ollmh/Sustainability_Projects/DSC07854.JPG',
    'images/ollmh/Sustainability_Projects/DSC07867.JPG',
    'images/ollmh/Sustainability_Projects/DSC07871.JPG',
    'images/ollmh/Sustainability_Projects/ollmhricefields2.gif',
    'images/ollmh/Sustainability_Projects/ricefield2.jpg',
    'images/ollmh/animated/graphics-nursing-315195.gif',
    'images/ollmh/animated/graphics-nursing-806801.gif',
    'images/ollmh/animated/graphics-welcome-731955.gif',
    'images/ollmh/developmentsnachievments/DSC00463.JPG',
    'images/ollmh/developmentsnachievments/DSC03927.JPG',
    'images/ollmh/developmentsnachievments/radiologybld.jpg',
    'images/ollmh/hospitalUnits/Agriculture/SAM_3186.JPG',
    'images/ollmh/hospitalUnits/Agriculture/SAM_3188.JPG',
    'images/ollmh/hospitalUnits/Dental_Unit_photos/DSCF7445.JPG',
    'images/ollmh/hospitalUnits/ICU/ICU.JPG',
    'images/ollmh/hospitalUnits/ICU/IcuA.JPG',
    'images/ollmh/hospitalUnits/ICU/IcuB.JPG',
    'images/ollmh/hospitalUnits/InPatient/DSC09662.JPG',
    'images/ollmh/hospitalUnits/InPatient/DSCF7526%20(2',
    'images/ollmh/hospitalUnits/InPatient/DSCF7526.JPG',
    'images/ollmh/hospitalUnits/InPatient/InpatientA.jpg',
    'images/ollmh/hospitalUnits/InPatient/InpatientB.jpg',
    'images/ollmh/hospitalUnits/InPatient/hospMatron.JPG',
    'images/ollmh/hospitalUnits/MiscDept/AcGikunju.JPG',
    'images/ollmh/hospitalUnits/MiscDept/DSCF7360.JPG',
    'images/ollmh/hospitalUnits/MiscDept/DSCF7388.JPG',
    'images/ollmh/hospitalUnits/MiscDept/DSCF7407.JPG',
    'images/ollmh/hospitalUnits/MiscDept/DSCF7409.JPG',
    'images/ollmh/hospitalUnits/MiscDept/OLLS1.JPG',
    'images/ollmh/hospitalUnits/MiscDept/OLLS4.JPG',
    'images/ollmh/hospitalUnits/MiscDept/OLLS6.JPG',
    'images/ollmh/hospitalUnits/MiscDept/Sr.Josephine.JPG',
    'images/ollmh/hospitalUnits/MiscDept/adminB.JPG',
    'images/ollmh/hospitalUnits/Morgue/HearsNBishp.JPG',
    'images/ollmh/hospitalUnits/Morgue/Morgue1.JPG',
    'images/ollmh/hospitalUnits/Morgue/Morgue2.JPG',
    'images/ollmh/hospitalUnits/Morgue/NewHrseFrnt.JPG',
    'images/ollmh/hospitalUnits/Morgue/NewHsSide.JPG',
    'images/ollmh/hospitalUnits/Mwea',
    'images/ollmh/hospitalUnits/OutPatient/DSCF7421.JPG',
    'images/ollmh/hospitalUnits/OutPatient/outp2.jpg',
    'images/ollmh/hospitalUnits/maternity/DSCF7519.JPG',
    'images/ollmh/hospitalUnits/maternity/FAITH%20KARIUKI%20IN%20MATERNITY%20WARD%20GIVING%20ROUTINE%20IMMUNIZATION%20copy.gif',
    'images/ollmh/hospitalUnits/more_photos/DSC00460.JPG',
    'images/ollmh/misc_Select/DSCF7459.JPG',
    'images/ollmh/misc_Select/DSCF7461.JPG',
    'images/ollmh/misc_Select/DSCF7468.JPG',
    'images/ollmh/news_events/schdorm1.JPG',
    'images/ollmh/news_events/studentprac.JPG',
    'images/ollmh/news_events/studphoto2.JPG',
    'images/ollmh/outp2.jpg',
    'images/project_action.jpg',
    'images/structure.jpg',
    'templates/tx_finnix/images/apple_touch_icon.png',
    'templates/tx_finnix/images/style1/logo.png&quot;',
]

def download(url, filepath):
    if os.path.exists(filepath) and os.path.getsize(filepath) > 100:
        print(f"  SKIP (exists): {os.path.basename(filepath)}")
        return True
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={
                "User-Agent": USER_AGENT,
                "Accept": "*/*",
            })
            with urllib.request.urlopen(req, timeout=90) as resp:
                data = resp.read()
                os.makedirs(os.path.dirname(filepath), exist_ok=True)
                with open(filepath, "wb") as f:
                    f.write(data)
                return True
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = RETRY_DELAY * attempt
                print(f"  429 rate-limited – retry {attempt}/{MAX_RETRIES} in {wait}s …")
                time.sleep(wait)
            elif e.code in (404, 410):
                print(f"  HTTP {e.code} – not found: {url}")
                return False
            else:
                print(f"  HTTP {e.code}: {e.reason}")
                return False
        except Exception as e:
            print(f"  Error: {e}")
            if attempt < MAX_RETRIES:
                time.sleep(DELAY * attempt)
    return False


def main():
    print("=" * 64)
    print("  Download Missing Images from Wayback Machine")
    print("=" * 64)
    print(f"  Images to download: {len(MISSING_IMAGES)}")
    print(f"  Output folder: {DEST_BASE}/")
    print("=" * 64 + "\n")

    ok = 0
    fail = 0
    for i, path in enumerate(MISSING_IMAGES, 1):
        url = f"https://web.archive.org/web/{CANONICAL_TS}im_/http://{SITE}/{path}"
        filepath = os.path.join(DEST_BASE, path)
        print(f"[{i}/{len(MISSING_IMAGES)}] {os.path.basename(path)}")
        if download(url, filepath):
            ok += 1
        else:
            fail += 1
        time.sleep(DELAY)

    print(f"\n  Done: {ok} downloaded, {fail} failed")


if __name__ == "__main__":
    main()
